GOING TO JUMP_CAVE_S FROM BAGUS_CABIN
GOING TO MEDICINE_CAVE_FAIRY FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM MEDICINE_CAVE_FAIRY
GOING BACK FROM JUMP_CAVE_S
GOING TO MEDICINE_CAVE FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM MEDICINE_CAVE
GOING BACK FROM JUMP_CAVE_S
GOING TO EX_LIFE_SWAMP_1 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM EX_LIFE_SWAMP_1
GOING BACK FROM JUMP_CAVE_S
GOING TO BAGUS_CABIN FROM JUMP_CAVE_S
GOING BACK FROM BAGUS_CABIN
GOING TO LOST_WOODS_1 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM LOST_WOODS_1
GOING BACK FROM JUMP_CAVE_S
GOING TO LOST_WOODS_2 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM LOST_WOODS_2
GOING BACK FROM JUMP_CAVE_S
GOING TO LOST_WOODS_3 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM LOST_WOODS_3
GOING BACK FROM JUMP_CAVE_S
GOING TO LOST_WOODS_4 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM LOST_WOODS_4
GOING BACK FROM JUMP_CAVE_S
GOING TO LOST_WOODS_5 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM LOST_WOODS_5
GOING BACK FROM JUMP_CAVE_S
GOING TO HEART_CAVE FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM HEART_CAVE
GOING BACK FROM JUMP_CAVE_S
GOING TO CAVE_200P FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM CAVE_200P
GOING BACK FROM JUMP_CAVE_S
GOING TO P2 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM P2
GOING BACK FROM JUMP_CAVE_S
GOING TO P2_RED_JAR FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM P2_RED_JAR
GOING BACK FROM JUMP_CAVE_S
GOING TO RED_JAR_SWAMP FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM RED_JAR_SWAMP
GOING BACK FROM JUMP_CAVE_S
GOING TO FAIRY_TOWN_BOULDER_1 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM FAIRY_TOWN_BOULDER_1
GOING BACK FROM JUMP_CAVE_S
GOING TO LIFE_TOWN_BRIDGE_NS_1 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM LIFE_TOWN_BRIDGE_NS_1
GOING BACK FROM JUMP_CAVE_S
GOING TO LIFE_TOWN_BRIDGE_EW_1 FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM LIFE_TOWN_BRIDGE_EW_1
GOING BACK FROM JUMP_CAVE_S
GOING TO LIFE_TOWN_BRIDGE_NS_2 FROM LIFE_TOWN_BRIDGE_EW_1
GOING TO LIFE_TOWN_N FROM LIFE_TOWN_BRIDGE_NS_2
GOING TO LIFE_TOWN_BRIDGE_NS_2 FROM LIFE_TOWN_N
GOING BACK FROM LIFE_TOWN_BRIDGE_NS_2
GOING TO LIFE_TOWN_BRIDGE_EW_1 FROM LIFE_TOWN_BRIDGE_NS_2
GOING BACK FROM LIFE_TOWN_BRIDGE_EW_1
GOING TO FOREST_100P FROM LIFE_TOWN_BRIDGE_NS_2
GOING TO LIFE_TOWN_BRIDGE_NS_2 FROM FOREST_100P
GOING BACK FROM LIFE_TOWN_BRIDGE_NS_2
GOING TO LIFE_TOWN_FAIRY FROM JUMP_CAVE_S
GOING TO JUMP_CAVE_S FROM LIFE_TOWN_FAIRY
GOING BACK FROM JUMP_CAVE_S
GOING TO SHIELD_TOWN_BOULDER_2 FROM JUMP_CAVE_S
export default [
     "MEDICINE_CAVE_FAIRY",
     "MEDICINE_CAVE",
     "EX_LIFE_SWAMP_1",
     "LOST_WOODS_1",
     "LOST_WOODS_2",
     "LOST_WOODS_3",
     "LOST_WOODS_4",
     "LOST_WOODS_5",
     "HEART_CAVE",
     "CAVE_200P",
     "P2",
     "P2_RED_JAR",
     "RED_JAR_SWAMP",
     "FAIRY_TOWN_BOULDER_1",
     "LIFE_TOWN_BRIDGE_NS_1",
     "LIFE_TOWN_N",
     "FOREST_100P",
     "LIFE_TOWN_BRIDGE_NS_2",
     "LIFE_TOWN_BRIDGE_EW_1",
     "LIFE_TOWN_FAIRY",
     "SHIELD_TOWN_BOULDER_2",
     "JUMP_CAVE_S",
     "BAGUS_CABIN"
]
