export const WORLD_MAPPINGS = {
    0x0: "world",
    0x1: "west hyrule towns",
    0x2: "east hyrule towns",
    0x3: "palace set 1",
    0x4: "palace set 2",
    0x5: "grand palace"
}

export const WORLD_INDEX_MAPPINGS = {
    0x0: "west hyrule",
    0x1: "dm/maze island",
    0x2: "east hyrule"
}

const OVERWORLD_SMALL_OBJECTS = {
    0x0: {name: "headstone",                    height: 1, width: 1, type: "wide"},
    0x1: {name: "cross",                        height: 1, width: 1, type: "wide"},
    0x2: {name: "angled cross",                 height: 1, width: 1, type: "wide"},
    0x3: {name: "tree stump",                   height: 2, width: 1, type: "tall", solid: true},
    0x4: {name: "stone table",                  height: 4, width: 4, type: "tall", solid: true},
    0x5: {name: "zelda",                        height: 1, width: 2, type: "wide"},
    0x6: {name: "zelda",                        height: 1, width: 2, type: "wide"},
    0x7: {name: "pit",                          height: 1, width: 1, type: "wide"},
    0x8: {name: "cloud",                        height: 1, width: 1, type: "wide"},
    0x9: {name: "cloud",                        height: 1, width: 1, type: "wide"},
    0xA: {name: "cloud",                        height: 1, width: 1, type: "wide"},
    0xB: {name: "cloud",                        height: 1, width: 1, type: "wide"},
    0xC: {name: "cloud",                        height: 1, width: 1, type: "wide"},
    0xD: {name: "cloud",                        height: 1, width: 1, type: "wide"},
    0xE: {name: "cloud",                        height: 1, width: 1, type: "wide"},
    0xF: {name: "cloud",                        height: 1, width: 1, type: "wide"},
}

const OVERWORLD_LARGE_OBJECTS = [
{
    0x1: { name: "",                            height: 2, width: 1, type: "wide", solid: true},
    0x2: { name: "forest ceiling",              height: 2, width: 1, type: "wide"},
    0x3: { name: "forest ceiling",              height: 2, width: 1, type: "wide"},
    0x4: { name: "curtains",                    height: 2, width: 1, type: "wide"},
    0x5: { name: "forest ceiling",              height: 1, width: 1, type: "wide"},
    0x6: { name: "handy glove block",           height: 1, width: 1, type: "wide", solid: true, breakable: true},
    0x7: { name: "horizontal pit",              height: 1, width: 1, type: "wide"},
    0x8: { name: "single weed",                 height: 1, width: 1, type: "wide"},
    0x9: { name: "two weeds",                   height: 1, width: 1, type: "wide"},
    0xA: { name: "north castle steps",          height: 1, width: 1, type: "wide"},
    0xB: { name: "background bricks",           height: 1, width: 1, type: "wide"},
    0xC: { name: "volcano background",          height: 1, width: 1, type: "wide"},
    0xD: { name: "handy glove block",           height: 1, width: 1, type: "tall", solid: true, breakable: true},
    0xE: { name: "background tree",             height: 1, width: 1, type: "tall"},
    0xF: { name: "column",                      height: 1, width: 1, type: "tall"},
}, {
    0x1: { name: "",                            height: 2, width: 1, type: "wide"},
    0x2: { name: "rock floor",                  height: 2, width: 1, type: "wide", solid: true},
    0x3: { name: "rock ceiling",                height: 2, width: 1, type: "wide", solid: true},
    0x4: { name: "bridge",                      height: 2, width: 1, type: "wide", solid: true},
    0x5: { name: "cave blocks",                 height: 1, width: 1, type: "wide", solid: true},
    0x6: { name: "handy glove blocks",          height: 1, width: 1, type: "wide", solid: true, breakable: true},
    0x7: { name: "collapsing bridge",           height: 1, width: 1, type: "wide", solid: true, collapsing: true},
    0x8: { name: "single weed",                 height: 1, width: 1, type: "wide"},
    0x9: { name: "two weeds",                   height: 1, width: 1, type: "wide"},
    0xA: { name: "horizontal pit",              height: 1, width: 1, type: "wide"},
    0xB: { name: "background bricks",           height: 1, width: 1, type: "wide"},
    0xC: { name: "volcano background",          height: 1, width: 1, type: "wide"},
    0xD: { name: "handy glove block",           height: 1, width: 1, type: "tall", solid: true, breakable: true},
    0xE: { name: "rock floor",                  height: 2, width: 1, type: "wide", solid: true},
    0xF: { name: "stone spire",                 height: 2, width: 1, type: "tall", solid: true},
}
]

const TOWN_SMALL_OBJECTS = {
    0x0: { name: "open door grass",             height: 3, width: 1, type: "wide", clear: true},
    0x1: { name: "closed door grass",           height: 3, width: 1, type: "wide", clear: true},
    0x2: { name: "open door h bricks",          height: 3, width: 1, type: "wide", clear: true},
    0x3: { name: "open door v bricks",          height: 3, width: 1, type: "wide", clear: true},
    0x4: { name: "stone table",                 height: 1, width: 1, type: "wide"},
    0x5: { name: "chair",                       height: 1, width: 1, type: "wide"},
    0x6: { name: "?",                           height: 1, width: 1, type: "wide"},
    0x7: { name: "cloud",                       height: 1, width: 1, type: "wide"},
    0x8: { name: "table",                       height: 1, width: 1, type: "wide"},
    0x9: { name: "bench",                       height: 1, width: 1, type: "wide"},
    0xA: { name: "cross",                       height: 1, width: 1, type: "wide"},
    0xB: { name: "cloud",                       height: 1, width: 1, type: "wide"},
    0xC: { name: "cloud",                       height: 1, width: 1, type: "wide"},
    0xD: { name: "cloud",                       height: 1, width: 1, type: "wide"},
    0xE: { name: "cloud",                       height: 1, width: 1, type: "wide"},
    0xF: { name: "cloud",                       height: 1, width: 1, type: "wide"},
}

const TOWN_LARGE_OBJECTS = [
{
    0x1: { name: "",                            height: 2, width: 1, type: "wide", solid: true},
    0x2: { name: "cross thatched roof",         height: 2, width: 1, type: "wide", solid: true},
    0x3: { name: "gray vertical roof",          height: 2, width: 1, type: "wide", solid: true},
    0x4: { name: "green vertical roof",         height: 2, width: 1, type: "wide", solid: true},
    0x5: { name: "brick building",              height: 1, width: 1, type: "wide", toGround: true},
    0x6: { name: "white building",              height: 1, width: 1, type: "wide", toGround: true},
    0x7: { name: "grass building",              height: 1, width: 1, type: "wide", toGround: true},
    0x8: { name: "white brick wall",            height: 1, width: 1, type: "wide"},
    0x9: { name: "log building",                height: 1, width: 1, type: "wide", toGround: true},
    0xA: { name: "brown windows square",        height: 2, width: 1, type: "wide"},
    0xB: { name: "gray windows round",          height: 2, width: 1, type: "wide"},
    0xC: { name: "brown windows round",         height: 2, width: 1, type: "wide"},
    0xD: { name: "blue bricks",                 height: 2, width: 1, type: "wide", solid: true},
    0xE: { name: "column",                      height: 2, width: 1, type: "tall"},
    0xF: { name: "castle background bricks",    height: 1, width: 1, type: "tall"},
},{
    0x1: { name: "",                            height: 2, width: 1, type: "wide", solid: true},
    0x2: { name: "cross thatched roof",         height: 2, width: 1, type: "wide", solid: true},
    0x3: { name: "gray vertical roof",          height: 2, width: 1, type: "wide", solid: true},
    0x4: { name: "green vertical roof",         height: 2, width: 1, type: "wide", solid: true},
    0x5: { name: "brick building",              height: 1, width: 1, type: "wide", toGround: true},
    0x6: { name: "white building",              height: 1, width: 1, type: "wide", toGround: true},
    0x7: { name: "grass building",              height: 1, width: 1, type: "wide", toGround: true},
    0x8: { name: "white brick wall",            height: 1, width: 1, type: "wide", solid: true},
    0x9: { name: "log building",                height: 1, width: 1, type: "wide"},
    0xA: { name: "brown windows square",        height: 2, width: 1, type: "wide"},
    0xB: { name: "gray windows round",          height: 2, width: 1, type: "wide"},
    0xC: { name: "brown windows round",         height: 2, width: 1, type: "wide"},
    0xD: { name: "blue bricks",                 height: 2, width: 1, type: "tall", solid: true},
    0xE: { name: "column",                      height: 2, width: 1, type: "tall"},
    0xF: { name: "castle background bricks",    height: 1, width: 1, type: "tall"},
}
]

const PALACE_SMALL_OBJECTS = {
    0x0: { name: "window",                      height: 4, width: 1, type: "tall"},
    0x1: { name: "rightward unicorn",           height: 1, width: 1, type: "tall"},
    0x2: { name: "leftward wolf",               height: 1, width: 1, type: "tall"},
    0x3: { name: "crystal statue",              height: 5, width: 4, type: "tall"},
    0x4: { name: "crystal statue",              height: 5, width: 4, type: "wide"},
    0x5: { name: "locked door",                 height: 3, width: 1, type: "wide", locked: true},
    0x6: { name: "locked door",                 height: 3, width: 1, type: "wide", locked: true},
    0x7: { name: "cloud",                       height: 1, width: 1, type: "wide"},
    0x8: { name: "small cloud",                 height: 1, width: 1, type: "wide"},
    0x9: { name: "ironknuckle statue",          height: 2, width: 1, type: "wide"},
    0xA: { name: "small cloud",                 height: 1, width: 1, type: "wide"},
    0xB: { name: "small cloud",                 height: 1, width: 1, type: "wide"},
    0xC: { name: "small cloud",                 height: 1, width: 1, type: "wide"},
    0xD: { name: "small cloud",                 height: 1, width: 1, type: "wide"},
    0xE: { name: "small cloud",                 height: 1, width: 1, type: "wide"},
    0xF: { name: "small cloud",                 height: 1, width: 1, type: "wide"},
}

const PALACE_LARGE_OBJECTS = [
{
    0x1: { name: "horizontal pit",              height: 1, width: 1, type: "wide", clear: true},
    0x2: { name: "horizontal bricks",           height: 1, width: 1, type: "wide", solid: true},
    0x3: { name: "breakable blocks",            height: 1, width: 1, type: "wide", solid: true, breakable: true},
    0x4: { name: "steel blocks",                height: 1, width: 1, type: "wide", solid: true},
    0x5: { name: "breaking bridge",             height: 1, width: 1, type: "wide", solid: true, collapsing: true},
    0x6: { name: "breakable blocks",            height: 1, width: 1, type: "wide", solid: true, breakable: true},
    0x7: { name: "horizontal bricks",           height: 2, width: 1, type: "wide", solid: true},
    0x8: { name: "curtains",                    height: 2, width: 1, type: "wide"},
    0x9: { name: "breakable blocks",            height: 2, width: 1, type: "wide", solid: true, breakable: true},
    0xA: { name: "horizontal bricks",           height: 2, width: 1, type: "wide", solid: true},
    0xB: { name: "breakable blocks",            height: 1, width: 1, type: "tall", solid: true, breakable: true},
    0xC: { name: "walk-thru bricks",            height: 1, width: 1, type: "tall", clear: true},
    0xD: { name: "breakable blocks",            height: 1, width: 1, type: "tall", solid: true, breakable: true},
    0xE: { name: "pit",                         height: 2, width: 1, type: "tall", clear: true},
    0xF: { name: "horizontal pit",              height: 1, width: 1, type: "wide", clear: true, toGround: true},
},
{
    0x1: { name: "horizontal pit",              height: 1, width: 1, type: "wide", clear: true},
    0x2: { name: "horizontal bricks",           height: 1, width: 1, type: "wide", solid: true},
    0x3: { name: "breakable blocks",            height: 1, width: 1, type: "wide", solid: true, breakable: true},
    0x4: { name: "steel blocks",                height: 1, width: 1, type: "wide", solid: true},
    0x5: { name: "breaking bridge",             height: 1, width: 1, type: "wide", solid: true, collapsing: true},
    0x6: { name: "breakable blocks",            height: 1, width: 1, type: "wide", solid: true, breakable: true},
    0x7: { name: "horizontal bricks",           height: 2, width: 1, type: "wide", solid: true},
    0x8: { name: "curtains",                    height: 2, width: 1, type: "wide"},
    0x9: { name: "breakable blocks",            height: 2, width: 1, type: "wide", solid: true, breakable: true},
    0xA: { name: "horizontal bricks",           height: 2, width: 1, type: "wide", solid: true},
    0xB: { name: "breakable blocks",            height: 1, width: 1, type: "tall", solid: true, breakable: true},
    0xC: { name: "walk-thru bricks",            height: 1, width: 1, type: "tall", clear: true},
    0xD: { name: "breakable blocks",            height: 1, width: 1, type: "tall", solid: true, breakable: true},
    0xE: { name: "pit",                         height: 2, width: 1, type: "tall", clear: true},
    0xF: { name: "horizontal pit",              height: 1, width: 1, type: "wide", clear: true, toGround: true},
}
]

export const ENEMY_MAPPINGS = [
    {
        0x00: "Fairy",
        0x01: "Red Jar",
        0x02: "Locked Door",
        0x03: "Myu",
        0x04: "Bot (blue)",
        0x05: "Bit (red)",
        0x06: "Moa",
        0x07: "Ache",
        0x08: "crash",
        0x09: "crash",
        0x0A: "Acheman",
        0x0B: "Bubble generator",
        0x0C: "Rock Generator",
        0x0D: "Red Deeler",
        0x0E: "Blue Deeler",
        0x0F: "Bago Bago Generator",
        0x10: "Bago Bago",
        0x11: "Red Octoroc (Jumping Only)",
        0x12: "Red Octorock (Moving and Jumping)",
        0x13: "Elevator",
        0x14: "Orange Moblin",
        0x15: "Red Moblin",
        0x16: "Blue Moblin",
        0x17: "Orange Diara",
        0x18: "Red Diara",
        0x19: "Orange Goryia",
        0x1A: "Red Goryia",
        0x1B: "Blue Goryia",
        0x1C: "Lowder",
        0x1D: "Moby generator",
        0x1E: "Moby",
        0x1F: "Megmet",
        0x20: "Geldarm",
        0x21: "Dumb Moblin Generator",
        0x22: "Dumb Moblin",
    },
    {
        0x00: "Fairy",
        0x01: "Red Jar",
        0x02: "Locked Door",
        0x03: "Myu",
        0x04: "Bot (blue)",
        0x05: "Bit (red)",
        0x06: "Moa",
        0x07: "Ache",
        0x08: "crash",
        0x09: "crash",
        0x0A: "Acheman",
        0x0B: "Bubble generator",
        0x0C: "Rock Generator",
        0x0D: "Red Deeler",
        0x0E: "Blue Deeler",
        0x0F: "Bago Bago Generator",
        0x10: "Bago Bago",
        0x11: "Red Octoroc (Jumping Only)",
        0x12: "Red Octorock (Moving and Jumping)",
        0x13: "Elevator",
        0x14: "Orange Moblin",
        0x15: "Red Moblin",
        0x16: "Blue Moblin",
        0x17: "Orange Diara",
        0x18: "Red Diara",
        0x19: "Orange Goryia",
        0x1A: "Red Goryia",
        0x1B: "Blue Goryia",
        0x1C: "Lowder",
        0x1D: "Moby generator",
        0x1E: "Moby",
        0x1F: "Megmet",
        0x20: "Geldarm",
        0x21: "Dumb Moblin Generator",
        0x22: "Dumb Moblin",
    },
    {
        0x00: "Fairy",
        0x01: "Red Magic Jar",
        0x02: "Locked Door",
        0x03: "Myu",
        0x04: "Bot (blue)",
        0x05: "Bit (red)",
        0x06: "Moa",
        0x07: "Ache",
        0x08: "???",
        0x09: "???",
        0x0A: "Acheman",
        0x0B: "Bubble Generator",
        0x0C: "Rock Generator (messed up link-doll sprite in east hyrule)",
        0x0D: "Red Deeler",
        0x0E: "Blue Deeler",
        0x0F: "Bago Bago Generator",
        0x10: "Bago Bago",
        0x11: "Blue Octoroc (Jumping Only)",
        0x12: "Blue Octorock (Moving and Jumping)",
        0x13: "Elevator",
        0x14: "Tektite",
        0x15: "Eye",
        0x16: "Leever",
        0x17: "Boon",
        0x18: "Basilisk",
        0x19: "Scorpion",
        0x1A: "Red Lizalfo",
        0x1B: "Orange Lizalfo",
        0x1C: "Blue Lizalfo",
        0x1D: "Boulder Tossing Lizalfos",
    },
    {
        0x00: "Fairy",
        0x01: "Red Magic Jar",
        0x02: "Locked Door",
        0x03: "Myu",
        0x04: "Bot (blue)",
        0x05: "Bit (red)",
        0x06: "Moa",
        0x07: "Ache",
        0x08: "???",
        0x09: "???",
        0x0A: "Acheman",
        0x0B: "Bubble Generator",
        0x0C: "Rock Generator (messed up link-doll sprite in east hyrule)",
        0x0D: "Red Deeler",
        0x0E: "Blue Deeler",
        0x0F: "Bago Bago Generator",
        0x10: "Bago Bago",
        0x11: "Blue Octoroc (Jumping Only)",
        0x12: "Blue Octorock (Moving and Jumping)",
        0x13: "Elevator",
        0x14: "Tektite",
        0x15: "Eye",
        0x16: "Leever",
        0x17: "Boon",
        0x18: "Basilisk",
        0x19: "Scorpion",
        0x1A: "Red Lizalfo",
        0x1B: "Orange Lizalfo",
        0x1C: "Blue Lizalfo",
        0x1D: "Boulder Tossing Lizalfos",
    },
    {
        0x00: "Fairy",
        0x01: "Candle",
        0x02: "Locked Door",
        0x03: "Purple Kees",
        0x04: "Purple Bot",
        0x05: "Bit",
        0x06: "Purple Moa",
        0x07: "Purple Kees (again?)",
        0x08: "Gold colored girl, crashes game if you talk to her",
    },
    {
        0x00: "Fairy",
        0x01: "Item in Palace Sprite",
        0x02: "Locked Door",
        0x03: "Myu",
        0x04: "Bot",
        0x05: "Strike for Red Jar",
        0x06: "Slow Magic Stealing Skull",
        0x07: "Orange Moa",
        0x08: "Falling Block Generator",
        0x09: "Single falling block",
        0x0A: "Blue Skull Head",
        0x0B: "Rathead Generator",
        0x0C: "Rathead",
        0x0D: "Dripping Column",
        0x0E: "Fast Magic Stealing Skull",
        0x0F: "Bago Bago Generator",
        0x10: "Bago Bago",
        0x11: "Rope Jumping Only",
        0x12: "Rope Jumping and Moving",
        0x13: "Elevator",
        0x14: "Crystal Slot",
        0x15: "Crystal",
        0x16: "Energy ball shooter (to down-right)",
        0x17: "Energy ball shooter (to down-left)",
        0x18: "Orange Iron Knuckle",
        0x19: "Red Iron Knuckle",
        0x1A: "Blue Iron Knuckle",
        0x1B: "Wolf Head Generator",
        0x1C: "Wolf Head",
        0x1D: "Mago",
        0x1E: "Hammer Thrower",
        0x1F: "Red Stalfos",
        0x20: "Horse Head",
        0x21: "Helmethead/Gooma (5th Palace Boss)",
        0x22: "Helmethead's floating head",
        0x23: "Blue Stalfos",
    },
    {
        0x00: "Fairy",
        0x01: "Item in Palace sprite",
        0x02: "Locked Door",
        0x03: "Myu",
        0x04: "Bot",
        0x05: "Strike for Red Jar/Ironknuckle",
        0x06: "Slow Magic Stealing Skulls",
        0x07: "Orange Moa",
        0x08: "Falling Blocks Generator",
        0x09: "Single falling block",
        0x0A: "Blue Skull Head",
        0x0B: "Rathead Generator",
        0x0C: "Rathead",
        0x0D: "Dripping Column",
        0x0E: "Fast Magic Stealing Skulls",
        0x0F: "???",
        0x10: "Flame",
        0x11: "Rope",
        0x12: "???",
        0x13: "Elevator",
        0x14: "Crystal Slot",
        0x15: "Crystal",
        0x16: "Energy ball shooter (to down-right)",
        0x17: "Energy ball shooter (to down-left)",
        0x18: "Orange Iron Knuckle",
        0x19: "Red Iron Knuckle",
        0x1A: "Blue Iron Knuckle",
        0x1B: "Wolf Head Generator",
        0x1C: "Wolf Head",
        0x1D: "Wizrobe",
        0x1E: "Red Stalfos Knight",
        0x1F: "Doomknocker",
        0x20: "Blue Iron Knuckle on horse",
        0x21: "Dragon (6th palace boss)",
        0x22: "Wizard (4th palace boss)",
        0x23: "Blue Stalfos Knight",
    },
    {
        0x00: "Fairy",
        0x01: "Red Magic Jar",
        0x02: "Locked Door",
        0x03: "Myu",
        0x04: "Bot (blue)",
        0x05: "Bit (red)",
        0x06: "Moa",
        0x07: "Ache",
        0x08: "???",
        0x09: "???",
        0x0A: "Acheman",
        0x0B: "Bubble Generator",
        0x0C: "Rock Generator",
        0x0D: "Red Deeler",
        0x0E: "Blue Deeler",
        0x0F: "Fire Bago Bago Generator",
        0x10: "Fire Bago Bago",
        0x11: "Fire Rope Jumping Only",
        0x12: "Fire Rope Jumping and Moving",
        0x13: "Elevator",
        0x14: "Slow Magic Stealing Skull",
        0x15: "Fast Magic Stealing Skull",
        0x16: "Orange Skull Head",
        0x17: "Large Magic Stealing Skull",
        0x18: "Orange Dreadhawk",
        0x19: "Red Dreadhawk",
        0x1A: "Blue Dreadhawk",
        0x1B: "???",
        0x1C: "???",
        0x1D: "Firebird",
        0x1E: "King Bot",
        0x1F: "???",
        0x20: "Barrier for Grand Palace",
        0x21: "???",
        0x22: "Thunder Bird Boss",
        0x23: "Trigger for Dark Link battle",
    }
]

export const SMALL_OBJECTS = [
    OVERWORLD_SMALL_OBJECTS,
    OVERWORLD_SMALL_OBJECTS,
    OVERWORLD_SMALL_OBJECTS,
    OVERWORLD_SMALL_OBJECTS,
    TOWN_SMALL_OBJECTS,
    PALACE_SMALL_OBJECTS,
    PALACE_SMALL_OBJECTS,
    PALACE_SMALL_OBJECTS
]

export const LARGE_OBJECT_SETS = [
    OVERWORLD_LARGE_OBJECTS,
    OVERWORLD_LARGE_OBJECTS,
    OVERWORLD_LARGE_OBJECTS,
    OVERWORLD_LARGE_OBJECTS,
    TOWN_LARGE_OBJECTS,
    PALACE_LARGE_OBJECTS,
    PALACE_LARGE_OBJECTS,
    PALACE_LARGE_OBJECTS
]