export default {
    "BAGUS_CABIN": {
        "id": "BAGUS_CABIN",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 1,
        "mapNumber": 24,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "BUBBLE_CLIFF": {
        "id": "BUBBLE_CLIFF",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 6,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "CAVE_200P": {
        "id": "CAVE_200P",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 12,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "CAVE_A": {
        "id": "CAVE_A",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 42,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "DM_ENTRANCE"
        ],
        "linkRequirements": {}
    },
    "CAVE_B_E": {
        "id": "CAVE_B_E",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 1,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_B_W"
        ],
        "linkRequirements": {}
    },
    "CAVE_B_W": {
        "id": "CAVE_B_W",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 1,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_B_E"
        ],
        "linkRequirements": {}
    },
    "CAVE_C_E": {
        "id": "CAVE_C_E",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 2,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_C_W"
        ],
        "linkRequirements": {}
    },
    "CAVE_C_W": {
        "id": "CAVE_C_W",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 2,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_C_E"
        ],
        "linkRequirements": {}
    },
    "CAVE_D_E": {
        "id": "CAVE_D_E",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 4,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_D_W"
        ],
        "linkRequirements": {}
    },
    "CAVE_D_W": {
        "id": "CAVE_D_W",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 4,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_D_E"
        ],
        "linkRequirements": {}
    },
    "CAVE_E_N": {
        "id": "CAVE_E_N",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 3,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_E_S"
        ],
        "linkRequirements": {}
    },
    "CAVE_E_S": {
        "id": "CAVE_E_S",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 3,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_E_N"
        ],
        "linkRequirements": {}
    },
    "CAVE_F_E": {
        "id": "CAVE_F_E",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 5,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_F_W"
        ],
        "linkRequirements": {}
    },
    "CAVE_F_W": {
        "id": "CAVE_F_W",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 5,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_F_E"
        ],
        "linkRequirements": {}
    },
    "CAVE_I_N": {
        "id": "CAVE_I_N",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 7,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_I_S"
        ],
        "linkRequirements": {}
    },
    "CAVE_I_S": {
        "id": "CAVE_I_S",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 7,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_I_N"
        ],
        "linkRequirements": {}
    },
    "CAVE_J_E": {
        "id": "CAVE_J_E",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 6,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_J_W"
        ],
        "linkRequirements": {}
    },
    "CAVE_J_W": {
        "id": "CAVE_J_W",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 6,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_J_E"
        ],
        "linkRequirements": {}
    },
    "CAVE_K": {
        "id": "CAVE_K",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 43,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "DM_EXIT"
        ],
        "linkRequirements": {}
    },
    "CAVE_L_N": {
        "id": "CAVE_L_N",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 8,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_L_S"
        ],
        "linkRequirements": {}
    },
    "CAVE_L_S": {
        "id": "CAVE_L_S",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 8,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_L_N"
        ],
        "linkRequirements": {}
    },
    "CAVE_M_E": {
        "id": "CAVE_M_E",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 10,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_M_W"
        ],
        "linkRequirements": {}
    },
    "CAVE_M_W": {
        "id": "CAVE_M_W",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 10,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_M_E"
        ],
        "linkRequirements": {}
    },
    "CAVE_N_N": {
        "id": "CAVE_N_N",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 14,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_N_S"
        ],
        "linkRequirements": {}
    },
    "CAVE_N_S": {
        "id": "CAVE_N_S",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 14,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_N_N"
        ],
        "linkRequirements": {}
    },
    "CAVE_O_N": {
        "id": "CAVE_O_N",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 9,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_O_S"
        ],
        "linkRequirements": {}
    },
    "CAVE_O_S": {
        "id": "CAVE_O_S",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 9,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_O_N"
        ],
        "linkRequirements": {}
    },
    "CAVE_P_E": {
        "id": "CAVE_P_E",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 11,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_P_W"
        ],
        "linkRequirements": {}
    },
    "CAVE_P_W": {
        "id": "CAVE_P_W",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 11,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_P_E"
        ],
        "linkRequirements": {}
    },
    "CAVE_Q_E": {
        "id": "CAVE_Q_E",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 12,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_Q_W"
        ],
        "linkRequirements": {}
    },
    "CAVE_Q_W": {
        "id": "CAVE_Q_W",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 12,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_Q_E"
        ],
        "linkRequirements": {}
    },
    "CAVE_R_N": {
        "id": "CAVE_R_N",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 13,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_R_S"
        ],
        "linkRequirements": {}
    },
    "CAVE_R_S": {
        "id": "CAVE_R_S",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 13,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_R_N"
        ],
        "linkRequirements": {}
    },
    "DAZZLE_LIFE": {
        "id": "DAZZLE_LIFE",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 57,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_500P_BAG": {
        "id": "DEATH_VALLEY_500P_BAG",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 62,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_BATTLE_1": {
        "id": "DEATH_VALLEY_BATTLE_1",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 26,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_BATTLE_2": {
        "id": "DEATH_VALLEY_BATTLE_2",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 24,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_BATTLE_3": {
        "id": "DEATH_VALLEY_BATTLE_3",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 25,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_CAVE_1_ENTRANCE": {
        "id": "DEATH_VALLEY_CAVE_1_ENTRANCE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 16,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "DEATH_VALLEY_CAVE_1_EXIT"
        ],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_CAVE_1_EXIT": {
        "id": "DEATH_VALLEY_CAVE_1_EXIT",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 16,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "DEATH_VALLEY_CAVE_1_ENTRANCE"
        ],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_CAVE_2_ENTRANCE": {
        "id": "DEATH_VALLEY_CAVE_2_ENTRANCE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 20,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "DEATH_VALLEY_CAVE_2_EXIT"
        ],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_CAVE_2_EXIT": {
        "id": "DEATH_VALLEY_CAVE_2_EXIT",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 19,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "DEATH_VALLEY_CAVE_2_ENTRANCE"
        ],
        "linkRequirements": {}
    },
    "DEATH_VALLEY_RED_JAR": {
        "id": "DEATH_VALLEY_RED_JAR",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 62,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "DM_BRIDGE_EXIT_E": {
        "id": "DM_BRIDGE_EXIT_E",
        "type": "BRIDGE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 5,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "DM_BRIDGE_EXIT_W"
        ],
        "linkRequirements": {}
    },
    "DM_BRIDGE_EXIT_W": {
        "id": "DM_BRIDGE_EXIT_W",
        "type": "BRIDGE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 4,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "DM_BRIDGE_EXIT_E"
        ],
        "linkRequirements": {}
    },
    "DM_ENTRANCE": {
        "id": "DM_ENTRANCE",
        "type": "OTHER",
        "continent": 1,
        "mapSet": 0,
        "mapNumber": 42,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_A"
        ],
        "linkRequirements": {}
    },
    "DM_EXIT": {
        "id": "DM_EXIT",
        "type": "OTHER",
        "continent": 1,
        "mapSet": 0,
        "mapNumber": 43,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "CAVE_K"
        ],
        "linkRequirements": {}
    },
    "DM_MAGIC": {
        "id": "DM_MAGIC",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 26,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "EAST_HYRULE_BRIDGE": {
        "id": "EAST_HYRULE_BRIDGE",
        "type": "BRIDGE",
        "continent": 2,
        "mapSet": 0,
        "mapNumber": 40,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "MAZE_ISLAND_BRIDGE"
        ],
        "linkRequirements": {}
    },
    "ELEVATOR_CAVE_G_E_BL": {
        "id": "ELEVATOR_CAVE_G_E_BL",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 22,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "ELEVATOR_CAVE_G_W_BR",
            "ELEVATOR_CAVE_G_W_TR",
            "ELEVATOR_CAVE_G_E_TL"
        ],
        "linkRequirements": {}
    },
    "ELEVATOR_CAVE_G_E_TL": {
        "id": "ELEVATOR_CAVE_G_E_TL",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 23,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "ELEVATOR_CAVE_G_E_BL"
        ],
        "linkRequirements": {}
    },
    "ELEVATOR_CAVE_G_W_BR": {
        "id": "ELEVATOR_CAVE_G_W_BR",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 22,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "ELEVATOR_CAVE_G_E_BL"
        ],
        "linkRequirements": {}
    },
    "ELEVATOR_CAVE_G_W_TR": {
        "id": "ELEVATOR_CAVE_G_W_TR",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 23,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "ELEVATOR_CAVE_G_E_BL"
        ],
        "linkRequirements": {}
    },
    "ELEVATOR_CAVE_H_D_BL": {
        "id": "ELEVATOR_CAVE_H_D_BL",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 25,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "ELEVATOR_CAVE_H_N_BR",
            "ELEVATOR_CAVE_H_W_TR",
            "ELEVATOR_CAVE_H_E_TL"
        ],
        "linkRequirements": {}
    },
    "ELEVATOR_CAVE_H_E_TL": {
        "id": "ELEVATOR_CAVE_H_E_TL",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 24,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "ELEVATOR_CAVE_H_W_TR",
            "ELEVATOR_CAVE_H_N_BR",
            "ELEVATOR_CAVE_H_D_BL"
        ],
        "linkRequirements": {}
    },
    "ELEVATOR_CAVE_H_N_BR": {
        "id": "ELEVATOR_CAVE_H_N_BR",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 25,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "ELEVATOR_CAVE_H_D_BL",
            "ELEVATOR_CAVE_H_E_TL"
        ],
        "linkRequirements": {}
    },
    "ELEVATOR_CAVE_H_W_TR": {
        "id": "ELEVATOR_CAVE_H_W_TR",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 24,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "ELEVATOR_CAVE_H_D_BL",
            "ELEVATOR_CAVE_H_E_TL"
        ],
        "linkRequirements": {}
    },
    "EX_LIFE_BEACH": {
        "id": "EX_LIFE_BEACH",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 57,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "EX_LIFE_SWAMP_1": {
        "id": "EX_LIFE_SWAMP_1",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 51,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "FAIRY_CAVE": {
        "id": "FAIRY_CAVE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 19,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "FAIRY_CAVE_HOLE"
        ],
        "linkRequirements": {}
    },
    "FAIRY_CAVE_HOLE": {
        "id": "FAIRY_CAVE_HOLE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 18,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "FAIRY_CAVE"
        ],
        "linkRequirements": {
            "FAIRY_CAVE": [
                "FAIRY"
            ]
        }
    },
    "FAIRY_TOWN": {
        "id": "FAIRY_TOWN",
        "type": "TOWN",
        "continent": 0,
        "mapSet": 1,
        "mapNumber": 11,
        "passThrough": false,
        "ability": "DOWNSTAB",
        "abilityRequirements": [
            "JUMP"
        ],
        "spellRequirements": [
            "MEDICINE"
        ],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "FIRE_TOWN": {
        "id": "FIRE_TOWN",
        "type": "TOWN",
        "continent": 2,
        "mapSet": 2,
        "mapNumber": 14,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "FIRE_TOWN_CAVE_500P_BAG": {
        "id": "FIRE_TOWN_CAVE_500P_BAG",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 9,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "FIRE_TOWN_CAVE_ENTRANCE": {
        "id": "FIRE_TOWN_CAVE_ENTRANCE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 8,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "FIRE_TOWN_CAVE_EXIT"
        ],
        "linkRequirements": {}
    },
    "FIRE_TOWN_CAVE_EXIT": {
        "id": "FIRE_TOWN_CAVE_EXIT",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 8,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "FIRE_TOWN_CAVE_ENTRANCE"
        ],
        "linkRequirements": {}
    },
    "FIRE_TOWN_FAIRY": {
        "id": "FIRE_TOWN_FAIRY",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 45,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "FIRE_TOWN_FOREST_500P_BAG": {
        "id": "FIRE_TOWN_FOREST_500P_BAG",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 38,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "FIRE_TOWN_RED_JAR": {
        "id": "FIRE_TOWN_RED_JAR",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 57,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "FOREST_100P": {
        "id": "FOREST_100P",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 46,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "FOREST_50P": {
        "id": "FOREST_50P",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 43,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "GP": {
        "id": "GP",
        "type": "PALACE",
        "continent": 2,
        "mapSet": 5,
        "mapNumber": 0,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [
            "CRYSTALS"
        ],
        "completionRequirements": [
            "THUNDER",
            "DOWNSTAB",
            "HANDY_GLOVE"
        ],
        "links": [],
        "linkRequirements": {}
    },
    "HAMMER_CAVE": {
        "id": "HAMMER_CAVE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 15,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "HEART_CAVE": {
        "id": "HEART_CAVE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 16,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "HEART_CLIFF": {
        "id": "HEART_CLIFF",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 38,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "JUMP_CAVE_N": {
        "id": "JUMP_CAVE_N",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 9,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "JUMP_CAVE_S"
        ],
        "linkRequirements": {
            "JUMP_CAVE_S": "FAIRY | JUMP"
        }
    },
    "JUMP_CAVE_S": {
        "id": "JUMP_CAVE_S",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 11,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "JUMP_CAVE_N"
        ],
        "linkRequirements": {}
    },
    "JUMP_TOWN": {
        "id": "JUMP_TOWN",
        "type": "TOWN",
        "continent": 0,
        "mapSet": 1,
        "mapNumber": 5,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [
            "TROPHY"
        ],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "KINGS_TOMB": {
        "id": "KINGS_TOMB",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 1,
        "mapNumber": 60,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "LIFE_TOWN_BRIDGE_EW": {
        "id": "LIFE_TOWN_BRIDGE_EW",
        "type": "BRIDGE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 2,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "LIFE_TOWN_BRIDGE_NS": {
        "id": "LIFE_TOWN_BRIDGE_NS",
        "type": "BRIDGE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 1,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "LIFE_TOWN_FAIRY": {
        "id": "LIFE_TOWN_FAIRY",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 20,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "LIFE_TOWN_N": {
        "id": "LIFE_TOWN_N",
        "type": "TOWN",
        "continent": 0,
        "mapSet": 1,
        "mapNumber": 8,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "LIFE_TOWN_S"
        ],
        "linkRequirements": {
            "LIFE_TOWN_S": [
                "FAIRY | BAGU_SAUCE"
            ]
        }
    },
    "LIFE_TOWN_S": {
        "id": "LIFE_TOWN_S",
        "type": "TOWN",
        "continent": 0,
        "mapSet": 1,
        "mapNumber": 6,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "LIFE_TOWN_N"
        ],
        "linkRequirements": {
            "LIFE_TOWN_N": [
                "FAIRY | BAGU_SAUCE"
            ]
        }
    },
    "LOST_WOODS_1": {
        "id": "LOST_WOODS_1",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 44,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "LOST_WOODS_2": {
        "id": "LOST_WOODS_2",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 21,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "LOST_WOODS_3": {
        "id": "LOST_WOODS_3",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 22,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "LOST_WOODS_4": {
        "id": "LOST_WOODS_4",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 23,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "LOST_WOODS_5": {
        "id": "LOST_WOODS_5",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 23,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAGIC_CAVE": {
        "id": "MAGIC_CAVE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 45,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_BRIDGE": {
        "id": "MAZE_ISLAND_BRIDGE",
        "type": "BRIDGE",
        "continent": 1,
        "mapSet": 0,
        "mapNumber": 40,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "EAST_HYRULE_BRIDGE"
        ],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_CHILD": {
        "id": "MAZE_ISLAND_CHILD",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 37,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_FORCED_BATTLE_1": {
        "id": "MAZE_ISLAND_FORCED_BATTLE_1",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 35,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_FORCED_BATTLE_2": {
        "id": "MAZE_ISLAND_FORCED_BATTLE_2",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 34,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_FORCED_BATTLE_3": {
        "id": "MAZE_ISLAND_FORCED_BATTLE_3",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 47,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_FORCED_BATTLE_4": {
        "id": "MAZE_ISLAND_FORCED_BATTLE_4",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 49,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_FORCED_BATTLE_5": {
        "id": "MAZE_ISLAND_FORCED_BATTLE_5",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 50,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_FORCED_BATTLE_6": {
        "id": "MAZE_ISLAND_FORCED_BATTLE_6",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 51,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_FORCED_BATTLE_7": {
        "id": "MAZE_ISLAND_FORCED_BATTLE_7",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 48,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MAZE_ISLAND_MAGIC": {
        "id": "MAZE_ISLAND_MAGIC",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 36,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MEDICINE_CAVE": {
        "id": "MEDICINE_CAVE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 14,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "MEDICINE_CAVE_FAIRY": {
        "id": "MEDICINE_CAVE_FAIRY",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 20,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "NORTH_CASTLE": {
        "id": "NORTH_CASTLE",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 0,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P1": {
        "id": "P1",
        "type": "PALACE",
        "continent": 0,
        "mapSet": 3,
        "mapNumber": 0,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P2": {
        "id": "P2",
        "type": "PALACE",
        "continent": 0,
        "mapSet": 3,
        "mapNumber": 14,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [
            "HANDY_GLOVE"
        ],
        "links": [],
        "linkRequirements": {}
    },
    "P2_RED_JAR": {
        "id": "P2_RED_JAR",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 57,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P3": {
        "id": "P3",
        "type": "PALACE",
        "continent": 0,
        "mapSet": 4,
        "mapNumber": 0,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P4": {
        "id": "P4",
        "type": "PALACE",
        "continent": 1,
        "mapSet": 4,
        "mapNumber": 15,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P5": {
        "id": "P5",
        "type": "PALACE",
        "continent": 2,
        "mapSet": 3,
        "mapNumber": 35,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P5_500P_BAG": {
        "id": "P5_500P_BAG",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 33,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P5_HEART": {
        "id": "P5_HEART",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 7,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P6": {
        "id": "P6",
        "type": "PALACE",
        "continent": 2,
        "mapSet": 4,
        "mapNumber": 36,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [
            "RECORDER"
        ],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P6_500P_BAG": {
        "id": "P6_500P_BAG",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 44,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "P6_HEART": {
        "id": "P6_HEART",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 46,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "PARAPA_CAVE_N": {
        "id": "PARAPA_CAVE_N",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 7,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "PARAPA_CAVE_S"
        ],
        "linkRequirements": {}
    },
    "PARAPA_CAVE_S": {
        "id": "PARAPA_CAVE_S",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 7,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "PARAPA_CAVE_N"
        ],
        "linkRequirements": {}
    },
    "RAFT_DOCK_E": {
        "id": "RAFT_DOCK_E",
        "type": "DOCK",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 41,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "RAFT_DOCK_W"
        ],
        "linkRequirements": {
            "RAFT_DOCK_W": "RAFT"
        }
    },
    "RAFT_DOCK_W": {
        "id": "RAFT_DOCK_W",
        "type": "DOCK",
        "continent": 2,
        "mapSet": 0,
        "mapNumber": 41,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "RAFT_DOCK_E"
        ],
        "linkRequirements": {
            "RAFT_DOCK_E": "RAFT"
        }
    },
    "RED_JAR_CEM": {
        "id": "RED_JAR_CEM",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 56,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "RED_JAR_SWAMP": {
        "id": "RED_JAR_SWAMP",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 51,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "REFLECT_TOWN": {
        "id": "REFLECT_TOWN",
        "type": "TOWN",
        "continent": 2,
        "mapSet": 2,
        "mapNumber": 17,
        "passThrough": false,
        "ability": "UPSTAB",
        "abilityRequirements": [
            "FAIRY"
        ],
        "spellRequirements": [
            "CHILD"
        ],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "REFLECT_TOWN_CLIFF_1": {
        "id": "REFLECT_TOWN_CLIFF_1",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 6,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "REFLECT_TOWN_CLIFF_2": {
        "id": "REFLECT_TOWN_CLIFF_2",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 23,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "SHIELD_TOWN": {
        "id": "SHIELD_TOWN",
        "type": "TOWN",
        "continent": 0,
        "mapSet": 1,
        "mapNumber": 2,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "SPELL_TOWN": {
        "id": "SPELL_TOWN",
        "type": "TOWN",
        "continent": 2,
        "mapSet": 2,
        "mapNumber": 18,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "BIG_ITEM",
            "BIG_ITEM"
        ],
        "itemRequirements": [
            "SPELL",
            "MAGIC7"
        ],
        "entryRequirements": [
            "HAMMER"
        ],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "SPELL_TOWN_CAVE_ENTRANCE": {
        "id": "SPELL_TOWN_CAVE_ENTRANCE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 13,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "SPELL_TOWN_CAVE_EXIT"
        ],
        "linkRequirements": {}
    },
    "SPELL_TOWN_CAVE_EXIT": {
        "id": "SPELL_TOWN_CAVE_EXIT",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 14,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [
            "SPELL_TOWN_CAVE_ENTRANCE"
        ],
        "linkRequirements": {}
    },
    "THUNDER_TOWN": {
        "id": "THUNDER_TOWN",
        "type": "TOWN",
        "continent": 2,
        "mapSet": 2,
        "mapNumber": 23,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [
            "MAGIC8"
        ],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "THUNDER_TOWN_CAVE_500P_BAG": {
        "id": "THUNDER_TOWN_CAVE_500P_BAG",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 11,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "THUNDER_TOWN_E_BRIDGE": {
        "id": "THUNDER_TOWN_E_BRIDGE",
        "type": "BRIDGE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 1,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "THUNDER_TOWN_N_BRIDGE": {
        "id": "THUNDER_TOWN_N_BRIDGE",
        "type": "BRIDGE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 0,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "THUNDER_TOWN_SWAMP_LIFE": {
        "id": "THUNDER_TOWN_SWAMP_LIFE",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 51,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "TROPHY_CAVE": {
        "id": "TROPHY_CAVE",
        "type": "CAVE",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 33,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [
            "SMALL_ITEM"
        ],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "WILSON_FENCE_1": {
        "id": "WILSON_FENCE_1",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 2,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "WILSON_FENCE_2": {
        "id": "WILSON_FENCE_2",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 3,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "WILSON_FENCE_3": {
        "id": "WILSON_FENCE_3",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 4,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    },
    "WILSON_FENCE_4": {
        "id": "WILSON_FENCE_4",
        "type": "OTHER",
        "continent": 0,
        "mapSet": 0,
        "mapNumber": 5,
        "passThrough": false,
        "ability": "",
        "abilityRequirements": [],
        "spellRequirements": [],
        "items": [],
        "itemRequirements": [],
        "entryRequirements": [],
        "completionRequirements": [],
        "links": [],
        "linkRequirements": {}
    }
}
